name: build_and_tests
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup Python
        uses: actions/setup-python@v4.5.0

        with:
          python-version: "3.11.3"

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: '1.5.1'

      - name: Install requirements
        run: poetry install

      - name: Run black
        run: poetry run black . --check

      - name: Run Flake8
        run: poetry run flake8 .

      - name: build
        env:
            POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
            PIP_VERSION: ${{ secrets.WEBAPP_PIP_VERSION || '23.3.1' }}
            POETRY_VERSION: ${{ secrets.WEBAPP_POETRY_VERSION || '1.7.1' }}
            PYTHON_VERSION: ${{ secrets.WEBAPP_PYTHON_VERSION || '3.11.3' }}
            VERSION: ${{ secrets.WEBAPP_VERSION || 'dev' }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            PRIMARY_DATABASE_URL: ${{ secrets.PRIMARY_DATABASE_URL }}
            DEBUG_MODE: ${{ secrets.DEBUG_MODE }}
            ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
            PGADMIN_DEFAULT_EMAIL: ${{ secrets.PGADMIN_DEFAULT_EMAIL }}
            PGADMIN_DEFAULT_PASSWORD: ${{ secrets.PGADMIN_DEFAULT_PASSWORD }}
            DJANGO_SUPERUSER_USERNAME: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
            DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
        run: docker-compose up -d
            
      - name: Run tests
        run: docker exec bookstore.webapp bash run-test.sh

      - name: stop services
        run: docker-compose stop